#!/usr/bin/python3

import sys
import numpy as np
import csv
import codecs
import qiskit
from qiskit import QuantumCircuit, execute
from qiskit.providers.aer import QasmSimulator

qc = QuantumCircuit.from_qasm_file("circuit.qasm")
qc.draw()
qc.save_statevector()

backend = QasmSimulator()

job = execute(qc, backend)
result = job.result()

state_vector = result.get_statevector()

print(file=codecs.open('qubitstate_mem.txt', 'w','utf-8'),end="")
for i in range(len(np.asarray(state_vector))):
    print(str(state_vector[i].real)+"\t"+str(state_vector[i].imag), file=codecs.open('qubitstate_mem.txt', 'a','utf-8'))
        

#print("run until the end", file=codecs.open('circuit.qasm','a','utf-8'))
    
#f = open("Assets/demofile2.txt", "w")
#f.write("--File updated!")
#f.close()
